# Create image based off of the official Node image
FROM node

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/app

# Change directory so that our commands run inside this new dir
WORKDIR /usr/src/app

# Copy dependency definitions
COPY package.json /usr/src/app
COPY package-lock.json /usr/src/app

# Install dependecies

Run npm install

# Get all the code needed to run the app
COPY . /usr/src/app
COPY src /usr/src/app
COPY node_modules /usr/src/app
# Expose the port the app runs in
EXPOSE 4200

# Serve the app
CMD ["npm", "start"]
